#!/bin/bash
#
# chkconfig: 2345 55 25
# Description: ADG OpenResty init.d script.
#              To install: `install adg-openresty /etc/init.d/`
#              To enable on Debian: `update-rc.d -f adg-openresty defaults`
#              To enable on CentOS: `chkconfig --add adg-openresty`
#
### BEGIN INIT INFO
# Provides:          adg-openresty
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: adg-openresty init.d script
# Description:       ADG is a library for automatic drawing generation. OpenResty is a web application server based on Nginx.
### END INIT INFO
#

message() {
    printf "\033[$1m$2\033[0m\n"
}

die() {
    message 33 "$1"
    exit 1
}

prepend() {
    local old="${!1}"
    if [[ -z "$old" ]]; then
        # Empty list: initialize it with the passed-in folder
        declare -g $1="$2"
    elif [[ ":$old:" != *":$2:"* ]]; then
        # Folder not found: prepend it
        declare -g $1="$2:$old"
    fi
}

. $(dirname "$0")/env.conf

EXE="$openresty/nginx/sbin/nginx"
[ -x "$EXE" ] || die "$EXE has no permission to run."

CONF="$adg_openresty/conf/nginx.conf"
[ -f "$CONF" ] || die "$CONF doesn't exist."

if [ -d "$adg_openresty/adg" ]; then
    # Use the locally installed ADG library, if found
    prepend LD_LIBRARY_PATH "$adg_openresty/adg/lib"
    prepend GI_TYPELIB_PATH "$adg_openresty/adg/lib/girepository-1.0"
    prepend XDG_DATA_DIRS   "$adg_openresty/adg/share"
    export LD_LIBRARY_PATH GI_TYPELIB_PATH XDG_DATA_DIRS
fi

NAME=adg-openresty
DESC="ADG OpenResty Daemon"
DAEMON="$EXE -p $adg_openresty"
PID="$adg_openresty/logs/nginx.pid"

do_start() {
    if [ -f $PID ]; then
        message 33 "$DESC is already running or crashed."
        message 32 "$DESC: reopening $CONF ..."
        $DAEMON -s reopen -c $CONF
        sleep 1
        message 36 "$DESC: reopened."
    else
        message 32 "$DESC: starting $CONF ..."
        $DAEMON -c $CONF
        sleep 1
        message 36 "$DESC: started."
    fi
}

do_stop() {
    if [ ! -f $PID ]; then
        message 33 "$DESC isn't running."
    else
        message 32 "$DESC: stopping $CONF ..."
        $DAEMON -s stop -c $CONF
        sleep 1
        message 36 "$DESC: stopped."
    fi
}

do_reload() {
    if [ ! -f $PID ]; then
        message 33 "$PID doesn't exist: $DESC isn't running."
        message 32 "$DESC: starting $CONF ..."
        $DAEMON -c $CONF
        sleep 1
        message 36 "$DESC: started."
    else
        message 32 "$DESC: reloading $CONF ..."
        $DAEMON -s reload -c $CONF
        sleep 1
        message 36 "$DESC: reloaded."
    fi
}

do_quit() {
    if [ ! -f $PID ]; then
        message 33 "$PID doesn't exist: $DESC isn't running."
    else
        message 32 "$DESC: quitting $CONF ..."
        $DAEMON -s quit -c $CONF
        sleep 1
        message 36 "$DESC: quitted."
    fi
}

do_test() {
    message 32 "$DESC: testing $CONF ..."
    $DAEMON -t -c $CONF
}

do_info() {
    $DAEMON -V
}

do_interact() {
    # For OpenResty, these paths are set in conf/nginx.conf
    env -u LUA \
        LUA_PATH="$adg_openresty/modules/?.lua;;" \
        LUA_CPATH="$adg_openresty/modules/?.so;;" \
        "$openresty/luajit/bin/luajit"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    reload)
        do_reload
        ;;
    restart)
        do_stop
        do_start
        ;;
    quit)
        do_quit
        ;;
    test)
        do_test
        ;;
    info)
        do_info
        ;;
    interact)
        do_interact
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart|quit|test|info|interact}"
        exit 2
        ;;
esac

exit 0
